name: test
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  appleos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest
          - latest-stable
        platform:
          - runner: macos-latest
            destination: 'platform=macOS,arch=x86_64'
          - runner: macos-11.0
            destination: 'platform=macOS,arch=x86_64'
          #- runner: macos-11.0
          #  destination: 'platform=macOS,arch=arm64'
          # - runner: macos-latest
          #   destination: 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro'
          # - runner: macos-latest
          #   destination: 'platform=tvOS Simulator,OS=latest,name=Apple TV 4K'
    runs-on: ${{ matrix.platform.runner }}
    steps:
    - name: Select latest available Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests for ${{ matrix.platform.destination }}
      run: xcodebuild test -scheme Standards-Package -enableThreadSanitizer YES -destination '${{ matrix.platform.destination }}'

  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ver:
          - 5.2
          - 5.3
        os:
          - xenial
          - bionic
          - focal
          #- centos7
          - centos8
          - amazonlinux2
    container:
      image: swift:${{ matrix.ver }}-${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests for ${{ matrix.runner }}
      run: swift test --enable-test-discovery --sanitize=thread

  windows:
    runs-on: windows-latest
    steps:
      - name: Setup VS dev env
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install Swift snapshot
        run: |
          Install-Binary -Url "https://swift.org/builds/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2021-01-17-a/swift-DEVELOPMENT-SNAPSHOT-2021-01-17-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
      - name: Set Environment Variables
        run: |
          echo "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "DEVELOPER_DIR=C:\Library\Developer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Adjust Paths
        run: |
          echo "C:\Library\Swift-development\bin;C:\Library\icu-67\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Supporting Files
        run: |
          Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\ucrt\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.modulemap" -destination "$env:VCToolsInstallDir\include\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.apinotes" -destination "$env:VCToolsInstallDir\include\visualc.apinotes"
          Copy-Item "$env:SDKROOT\usr\share\winsdk.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\um\module.modulemap"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery
